---
- name: Greeting playbook for webhook events
  hosts: "{{ ansible_eda.event.payload.context.hostname }}"
  become: true
  tasks:
    - name: Fix SSH Root login permissions
      ansible.builtin.lineinfile:
        regexp: "^PermitRootLogin"
        line: "#PermitRootLogin yes"
        state: present
        path: /etc/ssh/sshd_config

    - name: Restart SSHD service
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: Restart insights-client collection
      ansible.builtin.command:
        insights-client
